version: 2

sources:
  - name: olist_raw
    description: "Raw data from Olist e-commerce CSV files loaded via Meltano"
    database: sctp-dsai-468313
    schema: olist_raw
    
    tables:
      - name: main_raw_customers
        description: "Raw customer data including location information"
        columns:
          - name: customer_id
            description: "Unique identifier for each customer"
            tests:
              - not_null
              - unique
          - name: customer_unique_id
            description: "Customer's unique identifier across the platform"
          - name: customer_zip_code_prefix
            description: "Customer's zip code prefix for location"
          - name: customer_city
            description: "Customer's city"
          - name: customer_state
            description: "Customer's state (2-letter Brazilian state code)"
            
      - name: main_raw_orders
        description: "Raw order data including timestamps and status"
        columns:
          - name: order_id
            description: "Unique identifier for each order"
            tests:
              - not_null
              - unique
          - name: customer_id
            description: "Reference to customer who placed the order"
          - name: order_status
            description: "Current status of the order"
          - name: order_purchase_timestamp
            description: "When the order was placed"
          - name: order_approved_at
            description: "When the order was approved"
          - name: order_delivered_carrier_date
            description: "When the order was delivered to carrier"
          - name: order_delivered_customer_date
            description: "When the order was delivered to customer"
          - name: order_estimated_delivery_date
            description: "Estimated delivery date"
            
      - name: main_raw_order_items
        description: "Raw order item data including product details and pricing"
        columns:
          - name: order_id
            description: "Reference to the order"
            tests:
              - not_null
          - name: order_item_id
            description: "Unique identifier for each item within an order"
            tests:
              - not_null
          - name: product_id
            description: "Reference to the product"
            tests:
              - not_null
          - name: seller_id
            description: "Reference to the seller"
            tests:
              - not_null
          - name: shipping_limit_date
            description: "Shipping deadline for the item"
          - name: price
            description: "Price of the item"
          - name: freight_value
            description: "Shipping cost for the item"
            
      - name: main_raw_order_payments
        description: "Raw payment data including payment methods and installments"
        columns:
          - name: order_id
            description: "Reference to the order"
            tests:
              - not_null
          - name: payment_sequential
            description: "Payment sequence number for the order"
          - name: payment_type
            description: "Type of payment method used"
          - name: payment_installments
            description: "Number of installments for the payment"
          - name: payment_value
            description: "Total payment amount"
            
      - name: main_raw_order_reviews
        description: "Raw customer review data including scores and comments"
        columns:
          - name: review_id
            description: "Unique identifier for each review"
            tests:
              - not_null
              - unique
          - name: order_id
            description: "Reference to the order being reviewed"
            tests:
              - not_null
          - name: review_score
            description: "Review score from 1 to 5"
          - name: review_comment_title
            description: "Title of the review comment"
          - name: review_comment_message
            description: "Full review comment message"
          - name: review_creation_date
            description: "When the review was created"
          - name: review_answer_timestamp
            description: "When the review was answered"
            
      - name: main_raw_products
        description: "Raw product data including categories and dimensions"
        columns:
          - name: product_id
            description: "Unique identifier for each product"
            tests:
              - not_null
              - unique
          - name: product_category_name
            description: "Product category name in Portuguese"
          - name: product_name_lenght
            description: "Length of the product name"
          - name: product_description_lenght
            description: "Length of the product description"
          - name: product_photos_qty
            description: "Number of product photos"
          - name: product_weight_g
            description: "Product weight in grams"
          - name: product_length_cm
            description: "Product length in centimeters"
          - name: product_height_cm
            description: "Product height in centimeters"
          - name: product_width_cm
            description: "Product width in centimeters"
            
      - name: main_raw_sellers
        description: "Raw seller data including location information"
        columns:
          - name: seller_id
            description: "Unique identifier for each seller"
            tests:
              - not_null
              - unique
          - name: seller_zip_code_prefix
            description: "Seller's zip code prefix for location"
          - name: seller_city
            description: "Seller's city"
          - name: seller_state
            description: "Seller's state (2-letter Brazilian state code)"
            
      - name: main_raw_geolocation
        description: "Raw geolocation data for Brazilian zip codes"
        columns:
          - name: geolocation_zip_code_prefix
            description: "Zip code prefix for location"
          - name: geolocation_lat
            description: "Latitude coordinate"
          - name: geolocation_lng
            description: "Longitude coordinate"
          - name: geolocation_city
            description: "City name"
          - name: geolocation_state
            description: "State name (2-letter Brazilian state code)"
            
      - name: main_raw_category_translation
        description: "Raw product category translation data (Portuguese to English)"
        columns:
          - name: product_category_name
            description: "Product category name in Portuguese"
          - name: product_category_name_english
            description: "Product category name in English"
