version: 2

# NOTE: No tests defined at source level because:
# 1. Raw tables have JSON structure (data column) not individual columns
# 2. Comprehensive data quality testing is implemented at staging and marts layers
# 3. Staging models extract and validate JSON data, marts models test business logic
# 4. This approach provides better test coverage and more meaningful validation

sources:
  - name: olist_raw
    description: "Raw data from Olist e-commerce CSV files loaded via Meltano"
    database: sctp-dsai-468313
    schema: olist_raw
    
    tables:
      - name: main_raw_customers
        description: "Raw customer data including location information"
        columns:
          - name: customer_id
            description: "Unique identifier for each customer (extracted from JSON data column)"
          - name: customer_unique_id
            description: "Customer's unique identifier across the platform (extracted from JSON data column)"
          - name: customer_zip_code_prefix
            description: "Customer's zip code prefix for location (extracted from JSON data column)"
          - name: customer_city
            description: "Customer's city (extracted from JSON data column)"
          - name: customer_state
            description: "Customer's state (2-letter Brazilian state code) (extracted from JSON data column)"
            
      - name: main_raw_orders
        description: "Raw order data including timestamps and status"
        columns:
          - name: order_id
            description: "Unique identifier for each order (extracted from JSON data column)"
          - name: customer_id
            description: "Reference to customer who placed the order (extracted from JSON data column)"
          - name: order_status
            description: "Current status of the order (extracted from JSON data column)"
          - name: order_purchase_timestamp
            description: "When the order was placed (extracted from JSON data column)"
          - name: order_approved_at
            description: "When the order was approved (extracted from JSON data column)"
          - name: order_delivered_carrier_date
            description: "When the order was delivered to carrier (extracted from JSON data column)"
          - name: order_delivered_customer_date
            description: "When the order was delivered to customer (extracted from JSON data column)"
          - name: order_estimated_delivery_date
            description: "Estimated delivery date (extracted from JSON data column)"
            
      - name: main_raw_order_items
        description: "Raw order item data including product details and pricing"
        columns:
          - name: order_id
            description: "Reference to the order (extracted from JSON data column)"
          - name: order_item_id
            description: "Unique identifier for each item within an order (extracted from JSON data column)"
          - name: product_id
            description: "Reference to the product (extracted from JSON data column)"
          - name: seller_id
            description: "Reference to the seller (extracted from JSON data column)"
          - name: shipping_limit_date
            description: "Shipping deadline for the item (extracted from JSON data column)"
          - name: price
            description: "Price of the item (extracted from JSON data column)"
          - name: freight_value
            description: "Shipping cost for the item (extracted from JSON data column)"
            
      - name: main_raw_order_payments
        description: "Raw payment data including payment methods and installments"
        columns:
          - name: order_id
            description: "Reference to the order (extracted from JSON data column)"
          - name: payment_sequential
            description: "Payment sequence number for the order (extracted from JSON data column)"
          - name: payment_type
            description: "Type of payment method used (extracted from JSON data column)"
          - name: payment_installments
            description: "Number of installments for the payment (extracted from JSON data column)"
          - name: payment_value
            description: "Total payment amount (extracted from JSON data column)"
            
      - name: main_raw_order_reviews
        description: "Raw customer review data including scores and comments"
        columns:
          - name: review_id
            description: "Unique identifier for each review (extracted from JSON data column)"
          - name: order_id
            description: "Reference to the order being reviewed (extracted from JSON data column)"
          - name: review_score
            description: "Review score from 1 to 5 (extracted from JSON data column)"
          - name: review_comment_title
            description: "Title of the review comment (extracted from JSON data column)"
          - name: review_comment_message
            description: "Full review comment message (extracted from JSON data column)"
          - name: review_creation_date
            description: "When the review was created (extracted from JSON data column)"
          - name: review_answer_timestamp
            description: "When the review was answered (extracted from JSON data column)"
            
      - name: main_raw_products
        description: "Raw product data including categories and dimensions"
        columns:
          - name: product_id
            description: "Unique identifier for each product (extracted from JSON data column)"
          - name: product_category_name
            description: "Product category name in Portuguese (extracted from JSON data column)"
          - name: product_name_lenght
            description: "Length of the product name (extracted from JSON data column)"
          - name: product_description_lenght
            description: "Length of the product description (extracted from JSON data column)"
          - name: product_photos_qty
            description: "Number of product photos (extracted from JSON data column)"
          - name: product_weight_g
            description: "Product weight in grams (extracted from JSON data column)"
          - name: product_length_cm
            description: "Product length in centimeters (extracted from JSON data column)"
          - name: product_height_cm
            description: "Product height in centimeters (extracted from JSON data column)"
          - name: product_width_cm
            description: "Product width in centimeters (extracted from JSON data column)"
            
      - name: main_raw_sellers
        description: "Raw seller data including location information"
        columns:
          - name: seller_id
            description: "Unique identifier for each seller (extracted from JSON data column)"
          - name: seller_zip_code_prefix
            description: "Seller's zip code prefix for location (extracted from JSON data column)"
          - name: seller_city
            description: "Seller's city (extracted from JSON data column)"
          - name: seller_state
            description: "Seller's state (2-letter Brazilian state code) (extracted from JSON data column)"
            
      - name: main_raw_geolocation
        description: "Raw geolocation data for Brazilian zip codes"
        columns:
          - name: geolocation_zip_code_prefix
            description: "Zip code prefix for location (extracted from JSON data column)"
          - name: geolocation_lat
            description: "Latitude coordinate (extracted from JSON data column)"
          - name: geolocation_lng
            description: "Longitude coordinate (extracted from JSON data column)"
          - name: geolocation_city
            description: "City name (extracted from JSON data column)"
          - name: geolocation_state
            description: "State name (2-letter Brazilian state code) (extracted from JSON data column)"
            
      - name: main_raw_category_translation
        description: "Raw product category translation data (Portuguese to English)"
        columns:
          - name: product_category_name
            description: "Product category name in Portuguese (extracted from JSON data column)"
          - name: product_category_name_english
            description: "Product category name in English (extracted from JSON data column)"
