version: 2

models:
  - name: stg_customers
    description: "Staging model for customer data with regional classifications"
    columns:
      - name: customer_key
        description: "Primary key for customer dimension"
        tests:
          - not_null
          - unique
      - name: customer_unique_id
        description: "Customer's unique identifier across the platform"
        tests:
          - not_null
      - name: customer_city
        description: "Customer's city"
        tests:
          - not_null
      - name: customer_state
        description: "Customer's state (2-letter Brazilian state code)"
        tests:
          - not_null
          - accepted_values:
              values: ['AC', 'AL', 'AM', 'AP', 'BA', 'CE', 'DF', 'ES', 'GO', 'MA', 'MG', 'MS', 'MT', 'PA', 'PB', 'PE', 'PI', 'PR', 'RJ', 'RN', 'RO', 'RR', 'RS', 'SC', 'SP', 'SE', 'TO']
      - name: customer_zip_prefix
        description: "Customer's zip code prefix for location"
        tests:
          - not_null
      - name: customer_region
        description: "Customer's geographic region (North, Northeast, Southeast, South, Central-West)"
        tests:
          - not_null
          - accepted_values:
              values: ['North', 'Northeast', 'Southeast', 'South', 'Central-West']
      - name: customer_economic_zone
        description: "Customer's economic classification zone"
        tests:
          - not_null
          - accepted_values:
              values: ['Amazon', 'Northeast', 'Southeast', 'South', 'Central']

  - name: stg_orders
    description: "Staging model for order data with delivery performance calculations"
    columns:
      - name: order_key
        description: "Primary key for order dimension"
        tests:
          - not_null
          - unique
      - name: order_status
        description: "Current status of the order"
        tests:
          - not_null
          - accepted_values:
              values: ['delivered', 'shipped', 'canceled', 'unavailable', 'invoiced', 'processing', 'approved', 'created']
      - name: order_purchase_timestamp
        description: "When the order was placed"
        tests:
          - not_null
      - name: order_approved_at
        description: "When the order was approved"
      - name: order_delivered_carrier_date
        description: "When the order was delivered to carrier"
      - name: order_delivered_customer_date
        description: "When the order was delivered to customer"
      - name: order_estimated_delivery_date
        description: "Estimated delivery date"
        tests:
          - not_null
      - name: days_to_delivery
        description: "Calculated days from purchase to delivery"
        tests:
          - not_null
          - dbt_utils.is_positive
      - name: delivery_vs_estimate_days
        description: "Difference between actual and estimated delivery days"
      - name: is_delivered_on_time
        description: "Boolean flag indicating if delivery was on time"
        tests:
          - not_null
          - accepted_values:
              values: [true, false]

  - name: stg_order_items
    description: "Staging model for order item data with pricing calculations"
    columns:
      - name: order_id
        description: "Reference to the order"
        tests:
          - not_null
          - relationships:
              to: ref('stg_orders')
              field: order_key
      - name: order_item_id
        description: "Unique identifier for each item within an order"
        tests:
          - not_null
      - name: product_id
        description: "Reference to the product"
        tests:
          - not_null
          - relationships:
              to: ref('stg_products')
              field: product_key
      - name: seller_id
        description: "Reference to the seller"
        tests:
          - not_null
          - relationships:
              to: ref('stg_sellers')
              field: seller_key
      - name: shipping_limit_date
        description: "Shipping deadline for the item"
        tests:
          - not_null
      - name: price
        description: "Price of the item"
        tests:
          - not_null
          - dbt_utils.is_positive
      - name: freight_value
        description: "Shipping cost for the item"
        tests:
          - not_null
          - dbt_utils.is_positive

  - name: stg_order_payments
    description: "Staging model for payment data with payment method aggregation"
    columns:
      - name: order_id
        description: "Reference to the order"
        tests:
          - not_null
          - relationships:
              to: ref('stg_orders')
              field: order_key
      - name: payment_sequential
        description: "Payment sequence number for the order"
        tests:
          - not_null
          - dbt_utils.is_positive
      - name: payment_type
        description: "Type of payment method used"
        tests:
          - not_null
          - accepted_values:
              values: ['credit_card', 'boleto', 'voucher', 'debit_card', 'not_defined']
      - name: payment_installments
        description: "Number of installments for the payment"
        tests:
          - not_null
          - dbt_utils.is_positive
      - name: payment_value
        description: "Total payment amount"
        tests:
          - not_null
          - dbt_utils.is_positive

  - name: stg_order_reviews
    description: "Staging model for customer review data with timing calculations"
    columns:
      - name: review_id
        description: "Unique identifier for each review"
        tests:
          - not_null
          - unique
      - name: order_id
        description: "Reference to the order being reviewed"
        tests:
          - not_null
          - relationships:
              to: ref('stg_orders')
              field: order_key
      - name: review_score
        description: "Review score from 1 to 5"
        tests:
          - not_null
          - accepted_values:
              values: [1, 2, 3, 4, 5]
      - name: review_comment_title
        description: "Title of the review comment"
      - name: review_comment_message
        description: "Full review comment message"
      - name: review_creation_date
        description: "When the review was created"
        tests:
          - not_null
      - name: review_answer_timestamp
        description: "When the review was answered"
      - name: days_to_review
        description: "Days from order purchase to review creation"
        tests:
          - not_null
          - dbt_utils.is_positive

  - name: stg_products
    description: "Staging model for product data with category translations and derived dimensions"
    columns:
      - name: product_key
        description: "Primary key for product dimension"
        tests:
          - not_null
          - unique
      - name: product_category_portuguese
        description: "Product category name in Portuguese"
        tests:
          - not_null
      - name: product_category_english
        description: "Product category name in English"
        tests:
          - not_null
      - name: product_weight_g
        description: "Product weight in grams"
        tests:
          - not_null
          - dbt_utils.is_positive
      - name: product_length_cm
        description: "Product length in centimeters"
        tests:
          - not_null
          - dbt_utils.is_positive
      - name: product_height_cm
        description: "Product height in centimeters"
        tests:
          - not_null
          - dbt_utils.is_positive
      - name: product_width_cm
        description: "Product width in centimeters"
        tests:
          - not_null
          - dbt_utils.is_positive
      - name: product_volume_cm3
        description: "Calculated product volume in cubic centimeters"
        tests:
          - not_null
          - dbt_utils.is_positive
      - name: product_photos_qty
        description: "Number of product photos"
        tests:
          - not_null
          - dbt_utils.is_positive
      - name: product_name_length
        description: "Length of the product name"
        tests:
          - not_null
          - dbt_utils.is_positive
      - name: product_description_length
        description: "Length of the product description"
        tests:
          - not_null
          - dbt_utils.is_positive

  - name: stg_sellers
    description: "Staging model for seller data with regional classifications"
    columns:
      - name: seller_key
        description: "Primary key for seller dimension"
        tests:
          - not_null
          - unique
      - name: seller_city
        description: "Seller's city"
        tests:
          - not_null
      - name: seller_state
        description: "Seller's state (2-letter Brazilian state code)"
        tests:
          - not_null
          - accepted_values:
              values: ['AC', 'AL', 'AM', 'AP', 'BA', 'CE', 'DF', 'ES', 'GO', 'MA', 'MG', 'MS', 'MT', 'PA', 'PB', 'PE', 'PI', 'PR', 'RJ', 'RN', 'RO', 'RR', 'RS', 'SC', 'SP', 'SE', 'TO']
      - name: seller_zip_prefix
        description: "Seller's zip code prefix for location"
        tests:
          - not_null
      - name: seller_region
        description: "Seller's geographic region (North, Northeast, Southeast, South, Central-West)"
        tests:
          - not_null
          - accepted_values:
              values: ['North', 'Northeast', 'Southeast', 'South', 'Central-West']
      - name: seller_economic_zone
        description: "Seller's economic classification zone"
        tests:
          - not_null
          - accepted_values:
              values: ['Amazon', 'Northeast', 'Southeast', 'South', 'Central']

  - name: stg_geolocation
    description: "Staging model for geolocation data with coordinate validation"
    columns:
      - name: geolocation_zip_code_prefix
        description: "Zip code prefix for location"
        tests:
          - not_null
      - name: geolocation_lat
        description: "Latitude coordinate"
        tests:
          - not_null
          - dbt_utils.is_between:
              min_value: -90
              max_value: 90
      - name: geolocation_lng
        description: "Longitude coordinate"
        tests:
          - not_null
          - dbt_utils.is_between:
              min_value: -180
              max_value: 180
      - name: geolocation_city
        description: "City name"
        tests:
          - not_null
      - name: geolocation_state
        description: "State name (2-letter Brazilian state code)"
        tests:
          - not_null
          - accepted_values:
              values: ['AC', 'AL', 'AM', 'AP', 'BA', 'CE', 'DF', 'ES', 'GO', 'MA', 'MG', 'MS', 'MT', 'PA', 'PB', 'PE', 'PI', 'PR', 'RJ', 'RN', 'RO', 'RR', 'RS', 'SC', 'SP', 'SE', 'TO']

  - name: stg_category_translation
    description: "Staging model for product category translation data (Portuguese to English)"
    columns:
      - name: product_category_name
        description: "Product category name in Portuguese"
        tests:
          - not_null
          - unique
      - name: product_category_name_english
        description: "Product category name in English"
        tests:
          - not_null
