olist_analytics:
  outputs:
    dev:
      dataset: olist_analytics
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}"
      location: US
      method: service-account
      priority: interactive
      project: "{{ env_var('GCP_PROJECT_ID', 'sctp-dsai-468313') }}"
      threads: 1
      type: bigquery
    prod:
      dataset: olist_analytics_prod
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}"
      location: US
      method: service-account
      priority: interactive
      project: "{{ env_var('GCP_PROJECT_ID', 'sctp-dsai-468313') }}"
      threads: 1
      type: bigquery
  target: dev
